### ISSUE TITLE
open  redminehost/estimate_timelog/report occur 500 error

### ISSUE THREAD

**Issue by archonwang** [toritori0318/redmine_estimate_timelog#11]
@toritori0318 , sorry that still contains error. please check it.

```
Started GET "/estimate_timelog/report" for 192.168.20.231 at 2017-05-08 10:32:35 +0800

ActionController::RoutingError (undefined method `verify' for EstimateTimelogController:Class):
  plugins/redmine_estimate_timelog/app/controllers/estimate_timelog_controller.rb:26:in `<class:EstimateTimelogController>'
  plugins/redmine_estimate_timelog/app/controllers/estimate_timelog_controller.rb:18:in `<top (required)>'


Started GET "/estimate_timelog/report" for 192.168.20.231 at 2017-05-08 10:32:36 +0800
Processing by EstimateTimelogController#report as */*
  Current user: hui.wang (id=8)
  Rendered plugins/redmine_estimate_timelog/app/views/estimate_timelog/report.html.erb within layouts/base (248.2ms)
Completed 500 Internal Server Error in 501ms (ActiveRecord: 2.6ms)

ActionView::Template::Error (undefined method `each' for nil:NilClass):
     9: <%= form_tag({:controller => 'estimate_timelog', :action => 'report',
    10:               :project_id => @project, :issue_id => @issue},
    11:             :method => :get, :id => 'query_form') do %>
    12:   <% @criterias.each do |criteria| %>
    13:     <%= hidden_field_tag 'criterias[]', criteria, :id => nil %>
    14:   <% end %>
    15:   <%# TODO: get rid of the project_id field, that should already be in the URL %>
  plugins/redmine_estimate_timelog/app/views/estimate_timelog/report.html.erb:12:in `block in _31c07f8c07218c8942c6ea840019f1a9'
  plugins/redmine_estimate_timelog/app/views/estimate_timelog/report.html.erb:9:in `_31c07f8c07218c8942c6ea840019f1a9'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Started GET "/issue_badge/issues_count" for 192.168.20.231 at 2017-05-08 10:32:38 +0800
Processing by IssueBadgeController#issues_count as JSON
  Current user: hui.wang (id=8)
  Rendered text template (0.0ms)
Completed 200 OK in 14ms (Views: 0.8ms | ActiveRecord: 4.1ms)
```

my environment is 
```
Environment:
  Redmine version                3.3.3.stable.16545
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
```

**Comment by toritori0318** [comment]
@archonwang 
This plugin is depends on [verification](https://github.com/rails/verification) .
https://github.com/toritori0318/redmine_estimate_timelog#%E5%BF%85%E9%A0%88%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3  

Did you install this?

**Comment by archonwang** [comment]
@toritori0318 , 
it seems I have not installed it. 
How to install it ？
Thanks.

**Comment by toritori0318** [comment]
@archonwang  Please try this. 
```
cd <redime_root>
cd plugins
git clone https://github.com/rails/verification.git

# restart redmine ...
```

**Comment by archonwang** [comment]
Thanks. it works.
