### ISSUE TITLE
undefined method `before_filter'

### ISSUE THREAD

**Issue by lobin-z0x50** [toritori0318/redmine_estimate_timelog#12]
いつも利用させて頂いています。
Redmine 4.1 で利用しようとすると、エラーになってしまいました。

- Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
- Redmine: 4.1.1
- Rails: 5.2.4
- EstimeteTimelog: 最新のmasterブランチ

```
=> Booting Puma
=> Rails 5.2.4.2 application starting in production
=> Run `rails server -h` for more startup options
/usr/share/redmine/plugins/redmine_estimate_timelog/app/controllers/estimate_timelog_controller.rb:22:in `<class:EstimateTimelogController>': undefined method `before_filt
er' for EstimateTimelogController:Class (NoMethodError)
Did you mean?  before_action
        from /usr/share/redmine/plugins/redmine_estimate_timelog/app/controllers/estimate_timelog_controller.rb:18:in `<top (required)>'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `block in require'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:257:in `load_dependency'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:291:in `require'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:378:in `block in require_or_load'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:37:in `block in load_interlock'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies/interlock.rb:13:in `loading'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:37:in `load_interlock'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:356:in `require_or_load'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:334:in `depend_on'
        from /var/lib/gems/2.5.0/gems/activesupport-5.2.4.2/lib/active_support/dependencies.rb:246:in `require_dependency'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `each'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:477:in `block in eager_load!'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `each'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:475:in `eager_load!'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/engine.rb:356:in `eager_load!'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `each'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `instance_exec'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:32:in `run'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
        from /usr/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each'
        from /usr/lib/ruby/2.5.0/tsort.rb:347:in `call'
        from /usr/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
        from /usr/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/initializable.rb:60:in `run_initializers'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/application.rb:361:in `initialize!'
        from /usr/share/redmine/config/environment.rb:16:in `<top (required)>'
        from config.ru:3:in `require'
        from config.ru:3:in `block in <main>'
        from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
        from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
        from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
        from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
        from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:27:in `app'
        from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
        from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:312:in `block in start'
        from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:379:in `handle_profiling'
        from /var/lib/gems/2.5.0/gems/rack-2.2.3/lib/rack/server.rb:311:in `start'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:53:in `start'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:142:in `tap'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/commands/server/server_command.rb:142:in `perform'
        from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/lib/gems/2.5.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/command/base.rb:69:in `perform'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/command.rb:46:in `invoke'
        from /var/lib/gems/2.5.0/gems/railties-5.2.4.2/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by toritori0318** [comment]
ご報告ありがとうございます。
最新のredmineでは未検証ですので動作しない可能性はあります。
時間があるときに調査いたします

**Comment by toritori0318** [comment]
@lobin-z0x50  お待たせいたしました。以下のパッチを当て Redmine 4.1.1 で動作することを確認しました。
d062d6b19b9ef75b025de6d2a197f9e49ffd75f1  

最新版(v0.7.0)をダウンロードしてお試しいただけますでしょうか？よろしくお願いいたします

**Comment by lobin-z0x50** [comment]
動作確認できました！
助かりました。ありがとうございました！
