### ISSUE TITLE
[0.6.0]redmine 3.3.0 で500エラー

### ISSUE THREAD

**Issue by am-ma** [toritori0318/redmine_estimate_timelog#5]
こんにちは。am と申します。
突然ですが、本日redmine 3.3.0環境へv0.6.0をインストールし、
メニューのリンクを押下したところ500エラーが発生しましたのでご報告します。
（なお、git cloneで導入しました）

```
Completed 500 Internal Server Error in 127ms (ActiveRecord: 1.2ms)

ActionView::Template::Error (undefined local variable or method `render_estimate_timelog_breadcrumb' for #<#<Class:0x007ff7e6200090>:0x007ff7e61eb528>
Did you mean?  render_unattached_menu_item):
    2: <%= link_to_if_authorized l(:button_log_time), {:controller => 'estimate_timelog', :action => 'edit', :project_id => @project, :issue_id => @issue}, :class => 'icon icon-time-add' %>
    3: </div>
    4:
    5: <%= render_estimate_timelog_breadcrumb %>
    6:
    7: <h2><%= l(:label_spent_time) %></h2>
    8:
  plugins/redmine_estimate_timelog/app/views/estimate_timelog/report.html.erb:5:in `_plugins_redmine_estimate_timelog_app_views_estimate_timelog_report_html_erb___2008705883321825016_70351347204520'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

バージョン

```
Environment:
  Redmine version                3.3.0.stable.15638
  Ruby version                   2.3.1-p112 (2016-04-26) [x86_64-linux]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               Mysql2
```

原因はわかりますでしょうか？
以上、よろしくお願いいたします。

**Comment by toritori0318** [comment]
返信遅れました。
こちらでもバージョンを合わせて動作確認してみましたが、エラー再現されずに正常動作しています。
ですのでちょっと原因まではわかりかねます…申し訳ありません

**Comment by am-kzl** [comment]
そうでしたか。それでは、こちらでももう少し調べてみますね。
お返事ありがとうございました。

**Comment by archonwang** [comment]
+1

**Comment by archonwang** [comment]
full logs

```
An ActionView::Template::Error occurred in estimate_timelog#report:
 
  undefined local variable or method `render_estimate_timelog_breadcrumb' for #<#<Class:0x007fe47812f750>:0x000000047511e8>
  plugins/redmine_estimate_timelog/app/views/estimate_timelog/report.html.erb:5:in `_plugins_redmine_estimate_timelog_app_views_estimate_timelog_report_html_erb__3255314122721697661_37168080'
 
 
-------------------------------
Request:
-------------------------------
 
* URL : http://192.168.1.41/estimate_timelog/report
  * HTTP Method: GET
  * IP address : 10.1.200.41
  * Parameters : {"controller"=>"estimate_timelog", "action"=>"report"}
  * Timestamp  : 2017-03-06 09:29:47 UTC
  * Server : jira
  * Rails root : /opt/redmine-3.3
  * Process: 13020
 
-------------------------------
Session:
-------------------------------
 
  * session id: "8d995ae472698a00faf55abc37041199"
  * data: {"session_id"=>"8d995ae472698a00faf55abc37041199",
   "user_id"=>8,
   "tk"=>"27929310fb7c0cdb5f4e90f97a44a993839d8ac8",
   "sudo_timestamp"=>1488785562,
   "_csrf_token"=>"A0Rm4wF+Cd6kCqybcA4jSpzaYHUxMQiKJmneJgUaEZY=",
   "recent_projects"=>[7, 2, 11, 37, 10],
   "query"=>
    {:project_id=>7,
     :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}},
     :group_by=>nil,
     :column_names=>nil,
     :totalable_names=>[:estimated_hours, :spent_hours]},
   "issues_index_sort"=>"id:desc",
   "per_page"=>25,
   "my_account_sort"=>"none",
   "my_show_api_key_sort"=>"none",
   "show_locked_contracts"=>true,
   "my_page_sort"=>"none"}
 
-------------------------------
Environment:
-------------------------------
 
  * GATEWAY_INTERFACE                              : CGI/1.2
  * HTTP_ACCEPT                                    : */*
  * HTTP_ACCEPT_ENCODING                           : gzip, deflate, sdch
  * HTTP_ACCEPT_LANGUAGE                           : zh-CN,zh;q=0.8,en;q=0.6
  * HTTP_CONNECTION                                : keep-alive
  * HTTP_COOKIE                                    : _redmine_session=TFM0Z0t5Snd5dG9jNG82Q2FhQ2FBekpLVnFjWDBOcWpENFkrdTlLQnZmbzhGWFpQWkxZQVdUS3huMFMxL3o3SFBkT2tqMldiUVFkQmFGVEY2TUplbGJkTC9PVlk5S3ZIcjhRcVY3bE9KRFhhZVpiSW5nRDFSVStZWXU1VVB0RWtNUUtiZTNtWnVTVmx4QmJVNlpwSGd2TWVTVVc2TEprNHdJVzRhRlZKZDBHU205Ym1pSUcrZlIrUXlHb2pjOTdrWVZYMjhhL3A5ajZyQlIrMEZtcDF2bDN6R1FpZlhFVHhzaGN2SzZPYmxUcUxOeWRnaXNybVI3OFRIaTNYZ092dGt4anVnaFRkL0d4UTRBeXlpL1p4bVU5WnlHNW1RMkxMSzhndVltV3NiaUVweWlVZTc2MFMrbkR2NDl6K25URkxhOWNPOWtYREk1enJiL1dUU0wyZklCVGxIdnNiR0RleVlTN1JMYStFcWtTSURPMC8zWHNmUUZrcUZSUW8rdmtxYmxIcFFQRVB4Zmlid3N3Y3dVVlUwaGI0T1JyaFVjUEtzWDNxYlByR0RKaXJLZ1ZXZFB1R0p1cCtISThkY2JrRFJJcW5Lb2MxTlg5VVJiMExTdlVpZmE3R1RDV0wrUm9TYnR0NkNFUnZmNDNqYXUzLzgzT1FMQStWOVFFcFh3OTVsajl5UVZWcGEwdzNIckFBVnJXQUpwM3dGTGVLTXBtN1RkOENOMXpMcmhuREN1S25IUmhhVkN3MzJ4amFuTzVZT2JmSTNUL1lnT3JUV1lUQnE1MGhqKzZjeFZSbnhSbWxqZHpHbzNhQzcybFV6RzlEQmF0VHE2aG9NdkJrMlNlSFZIVXZXdG16TTQrRFVIeHdTTDJadUNYM2E2SXZGZlZTZndtMmFDMlBEUGcwOFJlakRoRjFHMzkxQnc0ZFRhUk9QTDNEN2x3UFFUQVIrWlMzeDJjSDlhaUZCTmM3ZytOVVBHL3BDemdNSStaYitOeXN5bmhRVGVFRnl1K1BxcVE5akV3cGRPSkU2dUpjVVN4SjdQeERZbndKL1lJS211N05yNzd3TmU2dTc4WnVPUWRZb2dRa3JJL1lZbmNOYlRiVy0tbXZmMGIyUzZkWW5HY0VGdmQ2bld6QT09--7a45907ede077129a2ff5fe9c4c13275cfca8b42
  * HTTP_HOST                                      : 192.168.1.41
* HTTP_REFERER : http://192.168.1.41/estimate_timelog/report
  * HTTP_USER_AGENT                                : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
  * HTTP_VERSION                                   : HTTP/1.1
  * HTTP_X_REQUESTED_WITH                          : XMLHttpRequest
  * ORIGINAL_FULLPATH                              : /estimate_timelog/report
  * ORIGINAL_SCRIPT_NAME                           :
  * PATH_INFO                                      : /estimate_timelog/report
  * QUERY_STRING                                   :
  * REMOTE_ADDR                                    : 10.1.200.41
  * REQUEST_METHOD                                 : GET
  * REQUEST_PATH                                   : /estimate_timelog/report
  * REQUEST_URI                                    : /estimate_timelog/report
  * ROUTES_47427900_SCRIPT_NAME                    :
  * SCRIPT_NAME                                    :
  * SERVER_NAME                                    : 192.168.1.41
  * SERVER_PORT                                    : 80
  * SERVER_PROTOCOL                                : HTTP/1.1
  * SERVER_SOFTWARE                                : thin 1.7.0 codename Dunder Mifflin
  * action_controller.instance                     : #<EstimateTimelogController:0x007fe478006158>
  * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x000000025c8698>
  * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x00000004767010>
  * action_dispatch.cookies_digest                 :
  * action_dispatch.cookies_serializer             :
  * action_dispatch.encrypted_cookie_salt          : encrypted cookie
  * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
  * action_dispatch.http_auth_salt                 : http authentication
  * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x0000000427df68>
  * action_dispatch.logger                         : #<ActiveSupport::Logger:0x00000005b85c18>
  * action_dispatch.parameter_filter               : [:password]
  * action_dispatch.redirect_filter                : []
  * action_dispatch.remote_ip                      : 10.1.200.41
  * action_dispatch.request.accepts                : [#<Mime::Type:0x007fe478108470 @synonyms=[], @symbol=nil, @string="*/*", @hash=-4611452030944444295>]
  * action_dispatch.request.content_type           :
  * action_dispatch.request.formats                : [#<Mime::Type:0x007fe478108470 @synonyms=[], @symbol=nil, @string="*/*", @hash=-4611452030944444295>]
  * action_dispatch.request.parameters             : {"controller"=>"estimate_timelog", "action"=>"report"}
  * action_dispatch.request.path_parameters        : {:controller=>"estimate_timelog", :action=>"report"}
  * action_dispatch.request.query_parameters       : {}
  * action_dispatch.request.request_parameters     : {}
  * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"8d995ae472698a00faf55abc37041199", "user_id"=>8, "tk"=>"27929310fb7c0cdb5f4e90f97a44a993839d8ac8", "sudo_timestamp"=>1488785562, "_csrf_token"=>"A0Rm4wF+Cd6kCqybcA4jSpzaYHUxMQiKJmneJgUaEZY=", "recent_projects"=>[7, 2, 11, 37, 10], "query"=>{:project_id=>7, :filters=>{"status_id"=>{:operator=>"o", :values=>[""]}}, :group_by=>nil, :column_names=>nil, :totalable_names=>[:estimated_hours, :spent_hours]}, "issues_index_sort"=>"id:desc", "per_page"=>25, "my_account_sort"=>"none", "my_show_api_key_sort"=>"none", "show_locked_contracts"=>true, "my_page_sort"=>"none"}
  * action_dispatch.request_id                     : 3d78f7a2-3179-4a73-bfcf-02b731272e18
  * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x00000005a76278>
  * action_dispatch.secret_key_base                : 59dda17a42803617f96151518b9aeecb94e132c6f140123f1982e1c8ae15d0103ffa854c4d8b0019
  * action_dispatch.secret_token                   :
  * action_dispatch.show_detailed_exceptions       : false
  * action_dispatch.show_exceptions                : true
  * action_dispatch.signed_cookie_salt             : signed cookie
  * async.callback                                 : #<Method: Thin::Connection#post_process>
  * async.close                                    : #<EventMachine::DefaultDeferrable:0x007fe485748968>
  * rack.errors                                    : #<IO:0x000000010315a0>
  * rack.input                                     : #<StringIO:0x007fe485749110>
  * rack.multiprocess                              : false
  * rack.multithread                               : true
  * rack.request.cookie_hash                       : {"_redmine_session"=>"TFM0Z0t5Snd5dG9jNG82Q2FhQ2FBekpLVnFjWDBOcWpENFkrdTlLQnZmbzhGWFpQWkxZQVdUS3huMFMxL3o3SFBkT2tqMldiUVFkQmFGVEY2TUplbGJkTC9PVlk5S3ZIcjhRcVY3bE9KRFhhZVpiSW5nRDFSVStZWXU1VVB0RWtNUUtiZTNtWnVTVmx4QmJVNlpwSGd2TWVTVVc2TEprNHdJVzRhRlZKZDBHU205Ym1pSUcrZlIrUXlHb2pjOTdrWVZYMjhhL3A5ajZyQlIrMEZtcDF2bDN6R1FpZlhFVHhzaGN2SzZPYmxUcUxOeWRnaXNybVI3OFRIaTNYZ092dGt4anVnaFRkL0d4UTRBeXlpL1p4bVU5WnlHNW1RMkxMSzhndVltV3NiaUVweWlVZTc2MFMrbkR2NDl6K25URkxhOWNPOWtYREk1enJiL1dUU0wyZklCVGxIdnNiR0RleVlTN1JMYStFcWtTSURPMC8zWHNmUUZrcUZSUW8rdmtxYmxIcFFQRVB4Zmlid3N3Y3dVVlUwaGI0T1JyaFVjUEtzWDNxYlByR0RKaXJLZ1ZXZFB1R0p1cCtISThkY2JrRFJJcW5Lb2MxTlg5VVJiMExTdlVpZmE3R1RDV0wrUm9TYnR0NkNFUnZmNDNqYXUzLzgzT1FMQStWOVFFcFh3OTVsajl5UVZWcGEwdzNIckFBVnJXQUpwM3dGTGVLTXBtN1RkOENOMXpMcmhuREN1S25IUmhhVkN3MzJ4amFuTzVZT2JmSTNUL1lnT3JUV1lUQnE1MGhqKzZjeFZSbnhSbWxqZHpHbzNhQzcybFV6RzlEQmF0VHE2aG9NdkJrMlNlSFZIVXZXdG16TTQrRFVIeHdTTDJadUNYM2E2SXZGZlZTZndtMmFDMlBEUGcwOFJlakRoRjFHMzkxQnc0ZFRhUk9QTDNEN2x3UFFUQVIrWlMzeDJjSDlhaUZCTmM3ZytOVVBHL3BDemdNSStaYitOeXN5bmhRVGVFRnl1K1BxcVE5akV3cGRPSkU2dUpjVVN4SjdQeERZbndKL1lJS211N05yNzd3TmU2dTc4WnVPUWRZb2dRa3JJL1lZbmNOYlRiVy0tbXZmMGIyUzZkWW5HY0VGdmQ2bld6QT09--7a45907ede077129a2ff5fe9c4c13275cfca8b42"}
  * rack.request.cookie_string                     : _redmine_session=TFM0Z0t5Snd5dG9jNG82Q2FhQ2FBekpLVnFjWDBOcWpENFkrdTlLQnZmbzhGWFpQWkxZQVdUS3huMFMxL3o3SFBkT2tqMldiUVFkQmFGVEY2TUplbGJkTC9PVlk5S3ZIcjhRcVY3bE9KRFhhZVpiSW5nRDFSVStZWXU1VVB0RWtNUUtiZTNtWnVTVmx4QmJVNlpwSGd2TWVTVVc2TEprNHdJVzRhRlZKZDBHU205Ym1pSUcrZlIrUXlHb2pjOTdrWVZYMjhhL3A5ajZyQlIrMEZtcDF2bDN6R1FpZlhFVHhzaGN2SzZPYmxUcUxOeWRnaXNybVI3OFRIaTNYZ092dGt4anVnaFRkL0d4UTRBeXlpL1p4bVU5WnlHNW1RMkxMSzhndVltV3NiaUVweWlVZTc2MFMrbkR2NDl6K25URkxhOWNPOWtYREk1enJiL1dUU0wyZklCVGxIdnNiR0RleVlTN1JMYStFcWtTSURPMC8zWHNmUUZrcUZSUW8rdmtxYmxIcFFQRVB4Zmlid3N3Y3dVVlUwaGI0T1JyaFVjUEtzWDNxYlByR0RKaXJLZ1ZXZFB1R0p1cCtISThkY2JrRFJJcW5Lb2MxTlg5VVJiMExTdlVpZmE3R1RDV0wrUm9TYnR0NkNFUnZmNDNqYXUzLzgzT1FMQStWOVFFcFh3OTVsajl5UVZWcGEwdzNIckFBVnJXQUpwM3dGTGVLTXBtN1RkOENOMXpMcmhuREN1S25IUmhhVkN3MzJ4amFuTzVZT2JmSTNUL1lnT3JUV1lUQnE1MGhqKzZjeFZSbnhSbWxqZHpHbzNhQzcybFV6RzlEQmF0VHE2aG9NdkJrMlNlSFZIVXZXdG16TTQrRFVIeHdTTDJadUNYM2E2SXZGZlZTZndtMmFDMlBEUGcwOFJlakRoRjFHMzkxQnc0ZFRhUk9QTDNEN2x3UFFUQVIrWlMzeDJjSDlhaUZCTmM3ZytOVVBHL3BDemdNSStaYitOeXN5bmhRVGVFRnl1K1BxcVE5akV3cGRPSkU2dUpjVVN4SjdQeERZbndKL1lJS211N05yNzd3TmU2dTc4WnVPUWRZb2dRa3JJL1lZbmNOYlRiVy0tbXZmMGIyUzZkWW5HY0VGdmQ2bld6QT09--7a45907ede077129a2ff5fe9c4c13275cfca8b42
  * rack.request.query_hash                        : {}
  * rack.request.query_string                      :
  * rack.run_once                                  : false
  * rack.session                                   : #<ActionDispatch::Request::Session:0x007fe478007d00>
  * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x007fe478007cb0>
  * rack.url_scheme                                : http
  * rack.version                                   : [1, 0]
 
-------------------------------
Backtrace:
-------------------------------
 
  plugins/redmine_estimate_timelog/app/views/estimate_timelog/report.html.erb:5:in `_plugins_redmine_estimate_timelog_app_views_estimate_timelog_report_html_erb__3255314122721697661_37168080'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by toritori0318** [comment]
@archonwang Thanks for the report.
However, it can not be reproduced...

I tried using this [Dockerfile/docker-compose](https://github.com/toritori0318/redmine/tree/verify_estimate_timelog/3.3).  

Is it possible to create a reproduction environment?

**Comment by toritori0318** [comment]
@am-ma @archonwang Fixed by 3f84c20

**Comment by archonwang** [comment]
@toritori0318 , sorry that still contains error. please check it.

```
Started GET "/estimate_timelog/report" for 192.168.20.231 at 2017-05-08 10:32:35 +0800

ActionController::RoutingError (undefined method `verify' for EstimateTimelogController:Class):
  plugins/redmine_estimate_timelog/app/controllers/estimate_timelog_controller.rb:26:in `<class:EstimateTimelogController>'
  plugins/redmine_estimate_timelog/app/controllers/estimate_timelog_controller.rb:18:in `<top (required)>'


Started GET "/estimate_timelog/report" for 192.168.20.231 at 2017-05-08 10:32:36 +0800
Processing by EstimateTimelogController#report as */*
  Current user: hui.wang (id=8)
  Rendered plugins/redmine_estimate_timelog/app/views/estimate_timelog/report.html.erb within layouts/base (248.2ms)
Completed 500 Internal Server Error in 501ms (ActiveRecord: 2.6ms)

ActionView::Template::Error (undefined method `each' for nil:NilClass):
     9: <%= form_tag({:controller => 'estimate_timelog', :action => 'report',
    10:               :project_id => @project, :issue_id => @issue},
    11:             :method => :get, :id => 'query_form') do %>
    12:   <% @criterias.each do |criteria| %>
    13:     <%= hidden_field_tag 'criterias[]', criteria, :id => nil %>
    14:   <% end %>
    15:   <%# TODO: get rid of the project_id field, that should already be in the URL %>
  plugins/redmine_estimate_timelog/app/views/estimate_timelog/report.html.erb:12:in `block in _31c07f8c07218c8942c6ea840019f1a9'
  plugins/redmine_estimate_timelog/app/views/estimate_timelog/report.html.erb:9:in `_31c07f8c07218c8942c6ea840019f1a9'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Started GET "/issue_badge/issues_count" for 192.168.20.231 at 2017-05-08 10:32:38 +0800
Processing by IssueBadgeController#issues_count as JSON
  Current user: hui.wang (id=8)
  Rendered text template (0.0ms)
Completed 200 OK in 14ms (Views: 0.8ms | ActiveRecord: 4.1ms)
```

my environment is 
```
Environment:
  Redmine version                3.3.3.stable.16545
  Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
```
