### ISSUE TITLE
Iconv(Ruby 2.0で削除)が使用されている

### ISSUE THREAD

**Issue by ito-nobuo** [toritori0318/redmine_estimate_timelog#9]
itoと申します。

git clone で使用させていただいたところ、
#5  #8　同様のエラーが発生しました。

Ruby 2.0以降削除された iconvが使用されているため、
参照エラーでヘルパーが動作していなかったようです。

公式のアナウンスに従いString#encodeへ置換したところ、ひとまず動作するようです。
変更内容をアップしますのでご確認いただけませんでしょうか。

```
Started GET "/redmine/estimate_timelog/report" for 127.0.0.1 at 2017-04-22 17:01:23 +0900
LoadError (No such file to load -- iconv):
  plugins/redmine_estimate_timelog/app/helpers/estimate_timelog_helper.rb:18:in `<top (required)>'
  plugins/redmine_estimate_timelog/app/controllers/estimate_timelog_controller.rb:18:in `<top (required)>'

Started GET "/redmine/estimate_timelog/report" for 127.0.0.1 at 2017-04-22 17:01:29 +0900
Processing by EstimateTimelogController#report as HTML
  Current user: ito.nobuo (id=5)
  Rendered plugins/redmine_estimate_timelog/app/views/estimate_timelog/report.html.erb within layouts/base (119.5ms)
Completed 500 Internal Server Error in 231ms (ActiveRecord: 17.6ms)

ActionView::Template::Error (undefined local variable or method `render_estimate_timelog_breadcrumb' for #<#<Class:0x0000000a371090>:0x0000000a37d070>):
    2: <%= link_to_if_authorized l(:button_log_time), {:controller => 'estimate_timelog', :action => 'edit', :project_id => @project, :issue_id => @issue}, :class => 'icon icon-time-add' %>
    3: </div>
    4: 
    5: <%= render_estimate_timelog_breadcrumb %>
    6: 
    7: <h2><%= l(:label_spent_time) %></h2>
    8: 
  plugins/redmine_estimate_timelog/app/views/estimate_timelog/report.html.erb:5:in `_plugins_redmine_estimate_timelog_app_views_estimate_timelog_report_html_erb__3116813930921029332_85744620'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by toritori0318** [comment]
@ito-nobuo ありがとうございます！動作問題無さそうですのでMR頂いてもよいでしょうか？

**Comment by ito-nobuo** [comment]
返信ありがとうございます。
PR送りましたのでご確認よろしくお願いいたします。

**Comment by toritori0318** [comment]
margeしました。ありがとうございます！
